export const config = {
    max: 50
}

export const languages = 
[ 
    {
        name: "ptbr",
        description: 'Português',
        flag: 'flagBR.png',
        e1: 'Item e quantidade são obrigatórios',
        e2: 'Máximo de ' + config.max + ' itens',
        e3: 'E-mail e senha devem ser informados',
        e4: 'E-mail ou senha inválidos',
        e5: 'Senha é muito pequena',
        e6: 'Nome da lista deve ser informado',
        e7: 'Exclua os itens primeiro',
        e8: 'E-mail já está na lista',
        e9: 'Acesso já criado',
        e10: 'Lista deve ter pelo menos 1 dono',
        e11: 'Lista deve estar vazia',
        e12: 'Você está offline, tente novamente mais tarde',
        e13: 'E-mail é inválido',
        e14: 'Todos os campos são obrigatórios',
        e15: 'Remova os acessos primeiro',
        e16: 'Conta já cadastrada! Para continuar, informe sua senha e clique em entrar.',
        e17: 'Conta $input$ já cadastrada! Faça seu login para vincular as contas.',
        e18: 'Erro! Limite de itens atingido!',
        e19: 'Arquivo com formato incorreto',
        e20: 'E-mail de verificação enviado! Confirme seu e-mail.',
        e21: 'Usuário não cadastrado! Cadastre-se!',
        t1: 'Nome',
        t2: 'Quantidade',
        t3: 'Incluir',
        t4: 'Novo Item',
        t5: 'Lista',
        t6: 'Senha',
        t7: 'Entrar',
        t8: 'Cadastrar',
        t9: 'Voltar',
        t10: 'Nova Lista',
        t11: 'Item',
        t12: 'Detalhe',
        t13: 'Compartilhar',
        t14: 'Conta',
        t15: 'Nova conta',
        t16: 'Pagador',
        t17: 'Data',
        t18: 'Valor',
        t19: 'Beneficiados',
        t20: 'Gerenciador de Listas',
        t21: 'Gerenciador de Contas',
        t22: 'Membros',    
        t23: 'Saldo',
        t24: 'Atenção',
        t25: 'Local',
        t26: 'Natureza',
        t27: 'Transporte',
        t28: 'Hospedagem',
        t29: 'Taxas',
        t30: 'Passeios',
        t31: 'Alimentação',
        t32: 'Diversos',
        t33: 'Selecione',
        t34: 'Responsável',
        t35: 'Multiplicador',
        t36: 'Calculado',
        t37: 'Excluir',
        t38: 'Editar',
        t39: 'Salvar',
        t40: 'Restaurar',
        t41: 'Ou acesse com:',
        t42: 'Selecione o idioma:',
        t43: 'Configuração',
        t44: 'Versão',
        t45: 'Dinheiro',
        m1: 'Selecione uma lista:',
        m2: 'Esqueci/Trocar minha senha',
        m3: 'E-mail para resetar senha enviado',
        m4: 'Nenhuma lista disponível',
        m5: 'Nenhum item foi adicionado',
        m6: 'Saldo negativo? Você deve',
        m7: 'Confirma exclusão?',
        m8: 'Somente o responsável pode excluir.',
        m9: 'Somente o responsável pode alterar.'
    }, 
    {
        name: "en",
        description: 'English',
        flag: 'flagUS.png',
        e1: 'Item name and amount are required',
        e2: 'Max of ' + config.max + ' items',
        e3: 'E-mail and password must be provided',
        e4: 'E-mail or password is wrong',
        e5: 'Passowrd must be at least 6 characters',    
        e6: 'List name are required',
        e7: 'Itens must be removed first',
        e8: 'E-mail already included',
        e9: 'Access already exists',
        e10: 'List must have at least one owner',
        e11: 'List must be empty',
        e12: 'You are offline, try again later',
        e13: 'E-mail is invalid',
        e14: 'All fields are required',
        e15: 'Remove access from others users first',
        e16: 'This account already exists. Inform the password and sign in.',
        e17: 'Account $input$ already exists. Sign in to link it each other.',
        e18: 'Error! Too many items!',
        e19: 'File not in correct format',
        e20: 'Confirmation e-mail sent! Check your e-mail.',
        e21: 'User not registered! Sign up!',
        t1: 'Name',
        t2: 'Amount',
        t3: 'Include',
        t4: 'New Item',
        t5: 'List',
        t6: 'Password',
        t7: 'Sign in',
        t8: 'Sign up',
        t9: 'Back to login',
        t10: 'New List',
        t11: 'Item',
        t12: 'Detail',
        t13: 'Share',
        t14: 'Expense',
        t15: 'New expense',
        t16: 'Payer',
        t17: 'Date',
        t18: 'Value',
        t19: 'Benefited',
        t20: 'List Mananger',
        t21: 'Expense Mananger',  
        t22: 'Members', 
        t23: 'Balance', 
        t24: 'Attention',
        t25: 'Place',
        t26: 'Type',
        t27: 'Transportation',
        t28: 'Hosting',
        t29: 'Taxes',
        t30: 'Recreation',
        t31: 'Food',
        t32: 'Others',   
        t33: 'Select', 
        t34: 'Owner',
        t35: 'Multiplier',
        t36: 'Calculated',
        t37: 'Remove',
        t38: 'Edit',
        t39: 'Save',
        t40: 'Restore',
        t41: 'Signin with:',
        t42: 'Select your language:',
        t43: 'Settings',
        t44: 'Version',
        t45: 'Money',
        m1: 'Select a list to continue',
        m2: 'Forgot/Change my password',
        m3: 'Reset password mail sent',
        m4: 'There is no list to display',
        m5: 'There is no item to display',
        m6: 'Negative balance? You owe',
        m7: 'Are you sure to delete?',
        m8: 'Only the owner is alowed to remove.',
        m9: 'Only the owner is alowed to edit.'
    },
    {
        name: "fr",
        description: 'Français',
        flag: 'flagFR.png',
        e1: 'Entrez l\'article et la quantité',
        e2: 'Maximum de ' + config.max + ' articles',
        e3: 'Entrez le e-mail e le mot de passe',
        e4: 'L’e-mail ou le mot de passe est incorrect',
        e5: 'Le mot de passe est trop court',
        e6: 'Entrez un nom pour la liste',
        e7: 'Supprimez l\'articles d’abord',
        e8: 'L’e-mail est déjà dans la liste',
        e9: 'L’accès existe déjà',
        e10: 'Au moins 1 propriétaire est obligatoire',
        e11: 'La liste doit être vide',
        e12: ' Veuillez vérifier votre connexion réseau et réessayer',
        e13: 'L’e-mail est incorrect',
        e14: 'Tous les champs sont obligatoires',
        e15: 'Supprimez l’accès d’abord',
        e16: 'Compte enregistré. Entrez le mot de passe et cliquez sur Me connecter.',
        e17: 'La compte $input$ est déjà enregistré! Connectez-vous pour associer les comptes.',
        e18: 'Impossible d\'ajouter. La limite a été atteinte.',
        e19: 'Le fichier n\'est pas au format correct',
        e20: 'Mail de confirmation envoyé! Vérifiez votre courrier électronique.',
        e21: 'Utilisateur non enregistré! Inscrivez-vous!',
        t1: 'Nom',
        t2: 'Quantité',
        t3: 'Ajouter',
        t4: 'Nouvel article',
        t5: 'Liste',
        t6: 'Mot de passe',
        t7: 'Me connecter',
        t8: 'Enregistrer',
        t9: 'Revenir',
        t10: 'Nouveau liste',
        t11: 'Article',
        t12: 'Accueil',
        t13: 'Partager',
        t14: 'Compte',
        t15: 'Nouveau compte',
        t16: 'Payeur',
        t17: 'Date',
        t18: 'Valeur',
        t19: 'Bénéficiaires',
        t20: 'Gestionnaire de listes',
        t21: 'Gestionnaire de comptes',
        t22: 'Membres',    
        t23: 'Solde',
        t24: 'Attention',
        t25: 'Lieu',
        t26: 'Catégorie',
        t27: 'Transport',
        t28: 'Logement',
        t29: 'Taxe',
        t30: 'Promenade',
        t31: 'Alimentation',
        t32: 'Autres',
        t33: 'Sélectionner',
        t34: 'Responsable',
        t35: 'Multiplicateur',
        t36: 'Valeur finale',
        t37: 'Supprimer',
        t38: 'Modifier',
        t39: 'Sauvegarder',
        t40: 'Restaurer',
        t41: 'Connectez-vous avec:',
        t42: 'Sélectionnez la langue:',
        t43: 'Configuration',
        t44: 'Version',
        t45: 'Argent',
        m1: 'Sélectionnez une liste:',
        m2: 'Mot de passe oublié/Modifier le mot de passe',
        m3: 'Nous vous avons envoyé un e-mail pour modifier votre mot de passe.',
        m4: 'Aucune liste disponible.',
        m5: 'Aucun article n’a été ajouté.',
        m6: 'Solde négatif? Vous avez une dette.',
        m7: 'Vous confirmez la suppression?',
        m8: 'Seulement le responsable peut supprimer.',
        m9: 'Seulement le responsable peut modifier.'
    }

]