export const config = {
    max: 50
}

export const languages = 
[ 
    {
        name: "ptbr",
        description: 'Português',
        flag: 'flagBR.png',
        e1: 'Item e quantidade são obrigatórios',
        e2: 'Máximo de ' + config.max + ' itens',
        e3: 'E-mail e senham devem ser informados',
        e4: 'E-mail ou senha inválidos',
        e5: 'Senha é muito pequena',
        e6: 'Nome da lista deve ser informado',
        e7: 'Exclua os itens primeiro',
        e8: 'E-mail já está na lista',
        e9: 'Acesso já criado',
        e10: 'Lista deve ter pelo menos 1 dono',
        e11: 'Lista deve estar vazia',
        e12: 'Você está offline, tente novamente mais tarde',
        e13: 'E-mail é inválido',
        e14: 'Todos os campos são obrigatórios',
        e15: 'Remova os acessos primeiro',
        e16: 'Conta já cadastrada! Para continuar, informe sua senha e clique em entrar.',
        e17: 'Conta $input$ já cadastrada! Faça seu login para vincular as contas.',
        e18: 'Erro! Limite de itens atingido!',
        t1: 'Nome',
        t2: 'Quantidade',
        t3: 'Incluir',
        t4: 'Novo Item',
        t5: 'Lista',
        t6: 'Senha',
        t7: 'Entrar',
        t8: 'Registrar',
        t9: 'Voltar',
        t10: 'Nova Lista',
        t11: 'Item',
        t12: 'Detalhe',
        t13: 'Acesso',
        t14: 'Conta',
        t15: 'Nova Conta',
        t16: 'Pagador',
        t17: 'Data',
        t18: 'Valor',
        t19: 'Beneficiados',
        t20: 'Gerenciador de Listas',
        t21: 'Gerenciador de Contas',
        t22: 'Membros',    
        t23: 'Saldo',
        t24: 'Atenção',
        t25: 'Local',
        t26: 'Natureza',
        t27: 'Transporte',
        t28: 'Hospedagem',
        t29: 'Taxas',
        t30: 'Passeios',
        t31: 'Alimentação',
        t32: 'Diversos',
        t33: 'Selecione',
        t34: 'Responsável',
        t35: 'Multiplicador',
        t36: 'Calculado',
        t37: 'Excluir',
        t38: 'Editar',
        t39: 'Salvar',
        t40: 'Restaurar',
        t41: 'Ou acesse com:',
        t42: 'Selecione o idioma:',
        t43: 'Configuração',
        t44: 'Versão',
        t45: 'Dinheiro',
        m1: 'Selecione uma lista:',
        m2: 'Esqueci/Trocar minha senha',
        m3: 'E-mail para resetar senha enviado',
        m4: 'Nenhuma lista disponível',
        m5: 'Nenhum item foi adicionado',
        m6: 'Saldo negativo? Você deve',
        m7: 'Confirma exclusão?',
        m8: 'Somente o responsável pode excluir.',
        m9: 'Somente o responsável pode alterar.'
    }, 
    {
        name: "en",
        description: 'English',
        flag: 'flagUS.png',
        e1: 'Item name and amount are required',
        e2: 'Max of ' + config.max + ' items',
        e3: 'E-mail and password must be provided',
        e4: 'E-mail or password is wrong',
        e5: 'Passowrd must be at least 6 characters',    
        e6: 'List name are required',
        e7: 'Itens must be removed first',
        e8: 'E-mail already included',
        e9: 'Access already exists',
        e10: 'List must have at least one owner',
        e11: 'List must be empty',
        e12: 'You are offline, try again later',
        e13: 'E-mail is invalid',
        e14: 'All fields are required',
        e15: 'Remove access from others users first',
        e16: 'This account already exists. Inform the password and sign in.',
        e17: 'Account $input$ already exists. Sign in to link it each other.',
        e18: 'Error! Too many items!',
        t1: 'Name',
        t2: 'Amount',
        t3: 'Include',
        t4: 'New Item',
        t5: 'List',
        t6: 'Password',
        t7: 'Sign in',
        t8: 'Sign up',
        t9: 'Back to login',
        t10: 'New List',
        t11: 'Item',
        t12: 'Detail',
        t13: 'Access',
        t14: 'Bill',
        t15: 'New Bill',
        t16: 'Payer',
        t17: 'Date',
        t18: 'Value',
        t19: 'Benefited',
        t20: 'List Mananger',
        t21: 'Bill Mananger',  
        t22: 'Members', 
        t23: 'Balance', 
        t24: 'Attention',
        t25: 'Place',
        t26: 'Type',
        t27: 'Transportation',
        t28: 'Hosting',
        t29: 'Taxes',
        t30: 'Recreation',
        t31: 'Food',
        t32: 'Others',   
        t33: 'Select', 
        t34: 'Owner',
        t35: 'Multiplier',
        t36: 'Calculated',
        t37: 'Remove',
        t38: 'Edit',
        t39: 'Save',
        t40: 'Restore',
        t41: 'Signin with:',
        t42: 'Select your language:',
        t43: 'Settings',
        t44: 'Version',
        t45: 'Money',
        m1: 'Select a list to continue',
        m2: 'Forgot/Change my password',
        m3: 'Reset password mail sent',
        m4: 'There is no list to display',
        m5: 'There is no item to display',
        m6: 'Negative balance? You owe',
        m7: 'Are you sure to delete?',
        m8: 'Only the owner is alowed to remove.',
        m9: 'Only the owner is alowed to edit.'
    }
]