export const config = {
    max: 50
}

export const language_ptbr = {
    e1: 'Item e quantidade são obrigatórios',
    e2: 'Máximo de ' + config.max + ' itens',
    e3: 'E-mail e senham devem ser informados',
    e4: 'E-mail ou senha inválidos',
    e5: 'Senha é muito pequena',
    e6: 'Nome da lista deve ser informado',
    e7: 'Exclua os itens primeiro',
    e8: 'E-mail inválido, não cadastrado ou já incluso',
    e9: 'Acesso já criado',
    e10: 'Lista deve ter pelo menos 1 dono',
    e11: 'Lista deve estar vazia',
    e12: 'Você está offline, tente novamente mais tarde',
    e13: 'E-mail é inválido',
    e14: 'Data, item, valor e beneficiado são obrigatórios',
    t1: 'Nome',
    t2: 'Quantidade',
    t3: 'Incluir',
    t4: 'Novo Item',
    t5: 'Lista',
    t6: 'Senha',
    t7: 'Entrar',
    t8: 'Registrar',
    t9: 'Voltar',
    t10: 'Nova Lista',
    t11: 'Item',
    t12: 'Início',
    t13: 'Acesso',
    t14: 'Conta',
    t15: 'Nova Conta',
    t16: 'Pagador',
    t17: 'Data',
    t18: 'Valor',
    t19: 'Beneficiados',
    t20: 'Gerenciador de Listas',
    t21: 'Gerenciador de Contas',
    m1: 'Selecione uma lista',
    m2: 'Esqueci minha senha',
    m3: 'E-mail para resetar senha enviado',
    m4: 'Nenhuma lista disponível',
    m5: 'Nenhum item foi adicionado'
}

export const language_en = {
    e1: 'Item name and amount are required',
    e2: 'Max of ' + config.max + ' items',
    e3: 'E-mail and password must be provided',
    e4: 'E-mail or password is wrong',
    e5: 'Passowrd must be at least 6 characters',    
    e6: 'List name are required',
    e7: 'Itens must be removed first',
    e8: 'E-mail invalid, not registered or already included',
    e9: 'Access already exists',
    e10: 'List must have at least one owner',
    e11: 'List must be empty',
    e12: 'You are offline, try again later',
    e13: 'E-mail is invalid',
    e14: 'Date, item, value and benefited are required',
    t1: 'Name',
    t2: 'Amount',
    t3: 'Include',
    t4: 'New Item',
    t5: 'List',
    t6: 'Password',
    t7: 'Sign in',
    t8: 'Sign up',
    t9: 'Back to login',
    t10: 'New List',
    t11: 'Item',
    t12: 'Home',
    t13: 'Access',
    t14: 'Bill',
    t15: 'New Bill',
    t16: 'Payer',
    t17: 'Date',
    t18: 'Value',
    t19: 'Benefited',
    t20: 'List Mananger',
    t21: 'Bill Mananger',    
    m1: 'Select a list to continue',
    m2: 'Forgot my password',
    m3: 'Reset password mail sent',
    m4: 'There is no list to display',
    m5: 'There is no item to display'    
}